comment: false

coverage:
  status:
    project:
      default:
        threshold: 10% # make CI green
    patch:
      default:
        threshold: 10% # make CI green

ignore: # ignore code coverage on following paths
  - "examples"
  - ".github"
  - "**/*.md"
  - "**/*.toml"
